# Generated by Django 4.0.6 on 2022-08-01 17:52

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.CharField(max_length=150, verbose_name="Address")),
                (
                    "state",
                    models.CharField(
                        max_length=50,
                        validators=[core.validators.state_validator],
                        verbose_name="state",
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        max_length=10,
                        validators=[core.validators.zip_code_validator],
                        verbose_name="Zip Code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy_holder",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Policy Number"
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Quote Number"
                    ),
                ),
                ("previously_cancel_policy", models.BooleanField(default=False)),
                (
                    "total_term_premium",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Total Term Premium",
                    ),
                ),
                (
                    "total_monthly_premium",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Monthly Term Premium",
                    ),
                ),
                (
                    "total_monthly_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Total Additional Fee",
                    ),
                ),
                (
                    "total_monthly_discount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Total Discount Monthly Fee",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.address"
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote",
                "verbose_name_plural": "Quotes",
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy_number",
                    models.CharField(max_length=50, verbose_name="Policy Number"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_cancel",
                    models.BooleanField(default=False, verbose_name="Cancel"),
                ),
                (
                    "total_monthly_premium",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Monthly Term Premium",
                    ),
                ),
                ("effective_date", models.DateTimeField(verbose_name="Effective Date")),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.address"
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.quote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy",
                "verbose_name_plural": "Policies",
            },
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["quote_number"], name="quote_number_unique"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["policy_holder"], name="policy_holder_unique"),
        ),
    ]
