# Generated by Django 4.0.6 on 2022-07-31 22:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_number', models.CharField(max_length=50, verbose_name='Policy Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_cancel', models.BooleanField(default=False, verbose_name='Cancel')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
            },
        ),
    ]
