# Generated by Django 4.0.6 on 2022-07-31 22:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_number', models.CharField(max_length=10, unique=True, verbose_name='Quote Number')),
                ('effective_date', models.DateTimeField(verbose_name='Effective Date')),
                ('total_term_premium', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Term Premium')),
                ('total_monthly_premium', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Monthly Term Premium')),
                ('total_additional_fee', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Additional Fee')),
                ('total_monthly_fee', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Additional Fee')),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Discount')),
                ('total_monthly_discount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Discount Monthly Fee')),
                ('previously_cancel_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.policy', verbose_name='Previously Cancel Policy')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['quote_number'], name='core_quote_quote_n_05175c_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['quote_number', 'effective_date'], name='core_quote_quote_n_6276a1_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['quote_number'], name='quote_number_unique'),
        ),
    ]
